# Generated by Django 4.1.5 on 2023-02-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOFTDESK', '0005_alter_contributors_user_alter_issue_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='permision',
            new_name='permision_V',
        ),
    ]
