# Generated by Django 4.1.5 on 2023-02-05 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOFTDESK', '0006_rename_permision_contributors_permision_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='SOFTDESK.project'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
