# Generated by Django 4.1.5 on 2023-02-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOFTDESK', '0009_alter_issue_assigned_to_alter_issue_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='issue',
            new_name='issue_id',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assigned_to',
            new_name='assigned_to_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='author_id',
        ),
    ]
