# Generated by Django 4.1.5 on 2023-02-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOFTDESK', '0011_rename_author_id_comments_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='permision_V',
            new_name='permission',
        ),
    ]
